import random

import pytest

from interplay import call_and_response
from rhythm import generate_rhythm


# --- P3.9: guitar rhythm reacts to another part -------------------------------


def test_call_and_response_echoes_every_other_hit_when_forced():
    other = generate_rhythm(8.0, [0.5], hit_chance=0.5, rng=random.Random(1))
    # echo_chance=1.0, base_hit_chance=0.0 -> the guitar hits EXACTLY where
    # the other part hits (pure echo), a deterministic, unambiguous
    # correlation check.
    guitar = call_and_response(other, base_hit_chance=0.0, rng=random.Random(2), echo_chance=1.0)
    assert len(guitar) == len(other)
    for o, g in zip(other, guitar):
        assert g["is_rest"] == o["is_rest"]
        assert g["duration"] == o["duration"]


def test_call_and_response_answers_on_a_later_slot():
    other = [
        {"duration": 0.5, "is_rest": False},
        {"duration": 0.5, "is_rest": True},
        {"duration": 0.5, "is_rest": True},
    ]
    # echo_chance=0.0 -> always answer, never echo the same slot.
    guitar = call_and_response(other, base_hit_chance=0.0, rng=random.Random(0), echo_chance=0.0, answer_gap=1)
    assert guitar[0]["is_rest"] is True  # not echoed
    assert guitar[1]["is_rest"] is False  # answered one slot later


def test_call_and_response_correlates_more_than_independent_noise():
    other = generate_rhythm(16.0, [0.25], hit_chance=0.5, rng=random.Random(3))
    other_hits = {i for i, c in enumerate(other) if not c["is_rest"]}

    guitar = call_and_response(other, base_hit_chance=0.3, rng=random.Random(4), echo_chance=0.7)
    guitar_hits = {i for i, c in enumerate(guitar) if not c["is_rest"]}

    overlap = len(other_hits & guitar_hits) / max(1, len(other_hits))

    # A guitar generated by plain independent rolling at base_hit_chance
    # would overlap other's hit slots at roughly base_hit_chance, not more.
    independent_guitar = [
        {"duration": c["duration"], "is_rest": not (random.Random(999 + i).random() < 0.3)}
        for i, c in enumerate(other)
    ]
    independent_hits = {i for i, c in enumerate(independent_guitar) if not c["is_rest"]}
    independent_overlap = len(other_hits & independent_hits) / max(1, len(other_hits))

    assert overlap > independent_overlap


def test_call_and_response_rejects_bad_input():
    other = [{"duration": 0.5, "is_rest": False}]
    with pytest.raises(ValueError):
        call_and_response(other, base_hit_chance=-0.1, rng=random.Random(0))
    with pytest.raises(ValueError):
        call_and_response(other, base_hit_chance=0.5, rng=random.Random(0), echo_chance=1.5)
    with pytest.raises(ValueError):
        call_and_response(other, base_hit_chance=0.5, rng=random.Random(0), answer_gap=-1)
